FROM --platform=linux/arm64/v8 elixir:1.16.1-slim AS build

ARG MIX_ENV=prod

RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force

RUN mkdir -p /opt/app
ADD . /opt/app/

WORKDIR /opt/app

RUN mix deps.get --only $MIX_ENV
RUN mix release --overwrite

FROM scratch AS app

WORKDIR /app
COPY --from=build /opt/app/_build/prod/peridiod-*.tar.gz ./

CMD ["/bin/bash"]
