FROM --platform=linux/arm64/v8 elixir:1.16.2-alpine AS build

ARG MIX_ENV=prod

RUN apk add --no-cache --update-cache \
      git \
      make

RUN mix archive.install github hexpm/hex branch latest --force
RUN /usr/local/bin/mix local.rebar --force

RUN mkdir -p /opt/app
ADD . /opt/app/

WORKDIR /opt/app

RUN mix deps.get --only $MIX_ENV
RUN mix release --overwrite

FROM scratch AS app
COPY --from=build /opt/app/_build/prod/peridiod-*.tar.gz ./arm64/
