FROM hexpm/elixir:1.17.2-erlang-27.0.1-ubuntu-jammy-20240530 AS build

ARG MIX_ENV=prod
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
    git make build-essential

RUN mix archive.install github hexpm/hex branch latest --force
RUN mix local.rebar --force


RUN mkdir -p /opt/app
ADD . /opt/app/

WORKDIR /opt/app

RUN mix deps.get --only $MIX_ENV
RUN mix release --overwrite

FROM scratch AS app
COPY --from=build /opt/app/_build/prod/peridiod-*.tar.gz .
