FROM hexpm/elixir:1.18.3-erlang-27.1.3-ubuntu-noble-20250127 AS build

ARG MIX_ENV=prod
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
    git make build-essential libmnl-dev

RUN mix archive.install github hexpm/hex branch latest --force
RUN mix local.rebar --force


RUN mkdir -p /opt/app
ADD . /opt/app/

WORKDIR /opt/app

RUN mix deps.get --only $MIX_ENV
RUN mix release --overwrite

FROM scratch AS app
COPY --from=build /opt/app/_build/prod/peridiod-*.tar.gz .
