FROM elixir:1.16.3-alpine AS build

ARG MIX_ENV=prod

RUN apk add --no-cache \
    linux-headers \
    build-base \
    gcc \
    automake \
    u-boot-tools \
    libsodium-dev \
    autoconf \
    libtool \
    libarchive-dev \
    confuse-dev \
    xdelta3 \
    dosfstools \
    help2man \
    curl \
    mtools \
    unzip \
    zip \
    make \
    git

RUN mix archive.install github hexpm/hex branch latest --force
RUN /usr/local/bin/mix local.rebar --force

# Build fwup here to ensure that its built for the arch
WORKDIR /opt
RUN git clone https://github.com/fwup-home/fwup --depth 1 --branch v1.10.2
WORKDIR /opt/fwup
RUN ./autogen.sh && PKG_CONFIG_PATH=$PKG_CONFIG_PATH ./configure --enable-shared=no && make && make install

RUN mkdir -p /opt/app
ADD . /opt/app/

WORKDIR /opt/app

RUN mix deps.get --only $MIX_ENV
RUN mix release --overwrite

FROM alpine:3.20 as app

RUN apk add --no-cache \
    agetty \
    confuse \
    libarchive \
    libstdc++ \
    libgcc \
    socat \
    iproute2  \
    iptables \
    uuidgen \
    openssl \
    u-boot-tools \
    wireguard-tools-wg-quick \
    openssh-server \
    coreutils

ENV PERIDIO_CONFIG_FILE=/etc/peridiod/peridio.json

RUN mkdir -p /etc/peridiod
RUN echo "echo \"Reboot Requested\"" > /usr/bin/reboot && chmod +x /usr/bin/reboot
RUN ln -s /etc/peridiod/fw_env.config /etc/fw_env.config

COPY --from=build /opt/app/priv/peridio-cert.pem /etc/peridiod/peridio-cert.pem
COPY --from=build /opt/app/_build/prod/rel/peridiod /opt/peridiod
COPY --from=build /opt/app/release/container-peridio.json /etc/peridiod/peridio.json
COPY --from=build /opt/fwup/src/fwup /usr/bin/fwup

WORKDIR /opt/peridiod

CMD ["/opt/peridiod/bin/peridiod", "start_iex"]
